// Gokul Hub Offline Mega-Lexicon
// Contains English, Tamil/Tanglish (ta), Hindi/Hinglish (hi), Spanish (es), and French (fr)

const translationLexicon = [
    // --- GREETINGS & POLITE PHRASES ---
    { en: "hello", ta: "வணக்கம் (Vanakkam)", hi: "नमस्ते (Namaste)", es: "Hola", fr: "Bonjour" },
    { en: "hi", ta: "வணக்கம் (Vanakkam)", hi: "नमस्ते (Namaste)", es: "Hola", fr: "Salut" },
    { en: "good morning", ta: "காலை வணக்கம் (Kaalai Vanakkam)", hi: "सुप्रभात (Suprabhat)", es: "Buenos días", fr: "Bonjour" },
    { en: "good afternoon", ta: "மதிய வணக்கம் (Madhiya Vanakkam)", hi: "शुभ दोपहर (Shubh Dophar)", es: "Buenas tardes", fr: "Bon après-midi" },
    { en: "good evening", ta: "மாலை வணக்கம் (Maalai Vanakkam)", hi: "शुभ संध्या (Shubh Sandhya)", es: "Buenas noches", fr: "Bonsoir" },
    { en: "good night", ta: "இனிய இரவு வணக்கம் (Iravu Vanakkam)", hi: "शुभ रात्रि (Shubh Ratri)", es: "Buenas noches", fr: "Bonne nuit" },
    { en: "thank you", ta: "நன்றி (Nandri)", hi: "धन्यवाद (Dhanyawad)", es: "Gracias", fr: "Merci" },
    { en: "thanks", ta: "நன்றி (Nandri)", hi: "शुक्रिया (Shukriya)", es: "Gracias", fr: "Merci" },
    { en: "welcome", ta: "நல்வரவு (Nalvaravu)", hi: "स्वागत है (Swagat hai)", es: "Bienvenido", fr: "Bienvenue" },
    { en: "please", ta: "தயவுசெய்து (Dhayavuseidhu)", hi: "कृपया (Kripaya)", es: "Por favor", fr: "S'il vous plaît" },
    { en: "sorry", ta: "மன்னிக்கவும் (Mannikkavum)", hi: "माफ़ करना (Maaf karna)", es: "Lo siento", fr: "Désolé" },
    { en: "excuse me", ta: "மன்னிக்கவும் (Mannikkavum)", hi: "माफ़ कीजिए (Maaf kijiye)", es: "Disculpe", fr: "Excusez-moi" },
    { en: "goodbye", ta: "போய் வருகிறேன் (Poi varugiren)", hi: "अलविदा (Alvida)", es: "Adiós", fr: "Au revoir" },
    { en: "bye", ta: "போய்ட்டு வரேன் (Poitu varen)", hi: "अलविदा (Alvida)", es: "Adiós", fr: "Salut" },
    { en: "yes", ta: "ஆம் (Aam / Aama)", hi: "हाँ (Haan)", es: "Sí", fr: "Oui" },
    { en: "no", ta: "இல்லை (Illai / Illa)", hi: "नहीं (Nahi)", es: "No", fr: "Non" },
    { en: "okay", ta: "சரி (Sari)", hi: "ठीक है (Theek hai)", es: "Vale / Está bien", fr: "D'accord" },
    
    // --- QUESTIONS & PRONOUNS ---
    { en: "how are you", ta: "எப்படி இருக்கிறீர்கள்? (Epdi irukka?)", hi: "आप कैसे हैं? (Kaise ho?)", es: "¿Cómo estás?", fr: "Comment ça va ?" },
    { en: "i am fine", ta: "நான் நன்றாக இருக்கிறேன் (Naan nalla irukken)", hi: "मैं ठीक हूँ (Main theek hoon)", es: "Estoy bien", fr: "Je vais bien" },
    { en: "what is your name", ta: "உங்கள் பெயர் என்ன? (Un peru enna?)", hi: "आपका नाम क्या है? (Tumhara naam kya hai?)", es: "¿Cómo te llamas?", fr: "Comment tu t'appelles ?" },
    { en: "my name is", ta: "என் பெயர் (En peyar...)", hi: "मेरा नाम ... है (Mera naam... hai)", es: "Me llamo", fr: "Je m'appelle" },
    { en: "where are you", ta: "எங்கே இருக்கிறீர்கள்? (Enga irukka?)", hi: "आप कहाँ हैं? (Kahan ho?)", es: "¿Dónde estás?", fr: "Où es-tu ?" },
    { en: "what are you doing", ta: "என்ன செய்கிறீர்கள்? (Enna panra?)", hi: "आप क्या कर रहे हैं? (Kya kar rahe ho?)", es: "¿Qué estás haciendo?", fr: "Que fais-tu ?" },
    { en: "who", ta: "யார் (Yaar)", hi: "कौन (Kaun)", es: "Quién", fr: "Qui" },
    { en: "what", ta: "என்ன (Enna)", hi: "क्या (Kya)", es: "Qué", fr: "Quoi" },
    { en: "where", ta: "எங்கே (Enga)", hi: "कहाँ (Kahan)", es: "Dónde", fr: "Où" },
    { en: "when", ta: "எப்பொழுது (Eppo)", hi: "कब (Kab)", es: "Cuándo", fr: "Quand" },
    { en: "why", ta: "ஏன் (Yen)", hi: "क्यों (Kyon)", es: "Por qué", fr: "Pourquoi" },
    { en: "how", ta: "எப்படி (Epdi)", hi: "कैसे (Kaise)", es: "Cómo", fr: "Comment" },
    { en: "i", ta: "நான் (Naan)", hi: "मैं (Main)", es: "Yo", fr: "Je" },
    { en: "you", ta: "நீ (Nee / Neengal)", hi: "तुम (Tum / Aap)", es: "Tú / Usted", fr: "Tu / Vous" },
    { en: "he", ta: "அவன் (Avan / Avar)", hi: "वह (Vah)", es: "Él", fr: "Il" },
    { en: "she", ta: "அவள் (Aval / Avanga)", hi: "वह (Vah)", es: "Ella", fr: "Elle" },
    { en: "we", ta: "நாங்கள் (Naangal / Namma)", hi: "हम (Hum)", es: "Nosotros", fr: "Nous" },
    { en: "they", ta: "அவர்கள் (Avanga)", hi: "वे (Ve)", es: "Ellos", fr: "Ils" },

    // --- FINANCE & VAULT SPECIFIC ---
    { en: "money", ta: "பணம் (Kaasu / Panam)", hi: "पैसा (Paisa)", es: "Dinero", fr: "Argent" },
    { en: "bank", ta: "வங்கி (Bank)", hi: "बैंक (Bank)", es: "Banco", fr: "Banque" },
    { en: "account", ta: "கணக்கு (Kanakku)", hi: "खाता (Khaata)", es: "Cuenta", fr: "Compte" },
    { en: "salary", ta: "சம்பளம் (Sambalam)", hi: "वेतन (Vetan / Pagar)", es: "Salario", fr: "Salaire" },
    { en: "income", ta: "வருமானம் (Varumaanam)", hi: "आय (Aamdani)", es: "Ingreso", fr: "Revenu" },
    { en: "expense", ta: "செலவு (Selavu)", hi: "खर्च (Kharcha)", es: "Gasto", fr: "Dépense" },
    { en: "loan", ta: "கடன் (Kadan)", hi: "कर्ज़ (Karz / Loan)", es: "Préstamo", fr: "Prêt" },
    { en: "debt", ta: "கடன் (Kadan)", hi: "कर्ज़ (Udhaar)", es: "Deuda", fr: "Dette" },
    { en: "balance", ta: "மீதம் (Meetham / Balance)", hi: "बकाया (Baqaya / Balance)", es: "Saldo", fr: "Solde" },
    { en: "price", ta: "விலை (Vilai)", hi: "कीमत (Keemat / Daam)", es: "Precio", fr: "Prix" },
    { en: "buy", ta: "வாங்கு (Vaangu)", hi: "खरीदना (Kharidna)", es: "Comprar", fr: "Acheter" },
    { en: "sell", ta: "விற்று (Vithu)", hi: "बेचना (Bechna)", es: "Vender", fr: "Vendre" },
    { en: "pay", ta: "செலுத்து (Kattu / Pay)", hi: "भुगतान (Bhugtan / Dena)", es: "Pagar", fr: "Payer" },
    { en: "work", ta: "வேலை (Vela)", hi: "काम (Kaam)", es: "Trabajo", fr: "Travail" },
    { en: "shift", ta: "ஷிப்ட் (Shift / Vela)", hi: "शिफ्ट (Shift)", es: "Turno", fr: "Service" },

    // --- TIME & DAYS ---
    { en: "time", ta: "நேரம் (Neram / Time)", hi: "समय (Samay / Waqt)", es: "Tiempo", fr: "Temps" },
    { en: "day", ta: "நாள் (Naal)", hi: "दिन (Din)", es: "Día", fr: "Jour" },
    { en: "week", ta: "வாரம் (Vaaram)", hi: "सप्ताह (Hafta)", es: "Semana", fr: "Semaine" },
    { en: "month", ta: "மாதம் (Maasam)", hi: "महीना (Mahina)", es: "Mes", fr: "Mois" },
    { en: "year", ta: "வருடம் (Varusham)", hi: "साल (Saal)", es: "Año", fr: "Année" },
    { en: "today", ta: "இன்று (Inniki)", hi: "आज (Aaj)", es: "Hoy", fr: "Aujourd'hui" },
    { en: "tomorrow", ta: "நாளை (Naalaiki)", hi: "कल (Kal)", es: "Mañana", fr: "Demain" },
    { en: "yesterday", ta: "நேற்று (Nethu)", hi: "कल (Kal)", es: "Ayer", fr: "Hier" },
    { en: "now", ta: "இப்போது (Ippo)", hi: "अभी (Abhi)", es: "Ahora", fr: "Maintenant" },
    { en: "morning", ta: "காலை (Kaalai)", hi: "सुबह (Subah)", es: "Mañana", fr: "Matin" },
    { en: "night", ta: "இரவு (Night / Iravu)", hi: "रात (Raat)", es: "Noche", fr: "Nuit" },

    // --- COMMON NOUNS ---
    { en: "water", ta: "தண்ணீர் (Thanni)", hi: "पानी (Paani)", es: "Agua", fr: "Eau" },
    { en: "food", ta: "உணவு (Saapadu)", hi: "खाना (Khana)", es: "Comida", fr: "Nourriture" },
    { en: "milk", ta: "பால் (Paal)", hi: "दूध (Doodh)", es: "Leche", fr: "Lait" },
    { en: "tea", ta: "தேநீர் (Tea)", hi: "चाय (Chai)", es: "Té", fr: "Thé" },
    { en: "coffee", ta: "காபி (Coffee)", hi: "कॉफ़ी (Coffee)", es: "Café", fr: "Café" },
    { en: "house", ta: "வீடு (Veedu)", hi: "घर (Ghar)", es: "Casa", fr: "Maison" },
    { en: "home", ta: "வீடு (Veedu)", hi: "घर (Ghar)", es: "Hogar", fr: "Maison" },
    { en: "office", ta: "அலுவலகம் (Office)", hi: "कार्यालय (Daftar)", es: "Oficina", fr: "Bureau" },
    { en: "shop", ta: "கடை (Kadai)", hi: "दुकान (Dukaan)", es: "Tienda", fr: "Boutique" },
    { en: "car", ta: "கார் (Car)", hi: "गाड़ी (Gaadi)", es: "Coche", fr: "Voiture" },
    { en: "bus", ta: "பேருந்து (Bus)", hi: "बस (Bus)", es: "Autobús", fr: "Bus" },
    { en: "road", ta: "சாலை (Road)", hi: "सड़क (Sadak)", es: "Camino", fr: "Route" },
    { en: "friend", ta: "நண்பன் (Nanban / Machi)", hi: "दोस्त (Dost / Bhai)", es: "Amigo", fr: "Ami" },
    { en: "family", ta: "குடும்பம் (Kudumbam)", hi: "परिवार (Parivar)", es: "Familia", fr: "Famille" },
    { en: "father", ta: "அப்பா (Appa)", hi: "पिता (Baap / Pita)", es: "Padre", fr: "Père" },
    { en: "mother", ta: "அம்மா (Amma)", hi: "माँ (Maa)", es: "Madre", fr: "Mère" },

    // --- VERBS / ACTIONS ---
    { en: "eat", ta: "சாப்பிடு (Saapidu)", hi: "खाना (Khao)", es: "Comer", fr: "Manger" },
    { en: "drink", ta: "குடி (Kudi)", hi: "पीना (Piyo)", es: "Beber", fr: "Boire" },
    { en: "sleep", ta: "தூங்கு (Thoongu)", hi: "सोना (So jao)", es: "Dormir", fr: "Dormir" },
    { en: "go", ta: "போ (Po)", hi: "जाना (Jao)", es: "Ir", fr: "Aller" },
    { en: "come", ta: "வா (Vaa)", hi: "आना (Aao)", es: "Venir", fr: "Venir" },
    { en: "stop", ta: "நில் / நிறுத்து (Nillu)", hi: "रुको (Ruko)", es: "Parar", fr: "Arrêter" },
    { en: "run", ta: "ஓடு (Odu)", hi: "दौड़ना (Daud)", es: "Correr", fr: "Courir" },
    { en: "walk", ta: "நட (Nada)", hi: "चलना (Chalo)", es: "Caminar", fr: "Marcher" },
    { en: "read", ta: "படி (Padi)", hi: "पढ़ना (Padho)", es: "Leer", fr: "Lire" },
    { en: "write", ta: "எழுது (Ezhudhu)", hi: "लिखना (Likho)", es: "Escribir", fr: "Écrire" },
    
    // --- EMOTIONS & ADJECTIVES ---
    { en: "good", ta: "நல்ல (Nalla / Super)", hi: "अच्छा (Achha)", es: "Bueno", fr: "Bon" },
    { en: "bad", ta: "மோசம் (Mosam / Ketta)", hi: "बुरा (Bura)", es: "Malo", fr: "Mauvais" },
    { en: "happy", ta: "மகிழ்ச்சி (Happy / Santhosham)", hi: "खुश (Khush)", es: "Feliz", fr: "Heureux" },
    { en: "sad", ta: "கவலை (Kavalai / Sad)", hi: "उदास (Udas)", es: "Triste", fr: "Triste" },
    { en: "angry", ta: "கோபம் (Kovam)", hi: "गुस्सा (Gussa)", es: "Enojado", fr: "En colère" },
    { en: "beautiful", ta: "அழகு (Azhagu)", hi: "सुंदर (Sundar)", es: "Hermoso", fr: "Beau" },
    { en: "big", ta: "பெரிய (Perusa)", hi: "बड़ा (Bada)", es: "Grande", fr: "Grand" },
    { en: "small", ta: "சிறிய (Chinnada)", hi: "छोटा (Chhota)", es: "Pequeño", fr: "Petit" },
    { en: "hot", ta: "சூடு (Sooda)", hi: "गरम (Garam)", es: "Caliente", fr: "Chaud" },
    { en: "cold", ta: "குளிர் (Kulir / Jilnu)", hi: "ठंडा (Thanda)", es: "Frío", fr: "Froid" },

    // --- NUMBERS ---
    { en: "one", ta: "ஒன்று (Onnu)", hi: "एक (Ek)", es: "Uno", fr: "Un" },
    { en: "two", ta: "இரண்டு (Rendu)", hi: "दो (Do)", es: "Dos", fr: "Deux" },
    { en: "three", ta: "மூன்று (Moonu)", hi: "तीन (Teen)", es: "Tres", fr: "Trois" },
    { en: "four", ta: "நான்கு (Naalu)", hi: "चार (Char)", es: "Cuatro", fr: "Quatre" },
    { en: "five", ta: "ஐந்து (Anju)", hi: "पांच (Paanch)", es: "Cinco", fr: "Cinq" },
    { en: "six", ta: "ஆறு (Aaru)", hi: "छह (Chhah)", es: "Seis", fr: "Six" },
    { en: "seven", ta: "ஏழு (Yezhu)", hi: "सात (Saat)", es: "Siete", fr: "Sept" },
    { en: "eight", ta: "எட்டு (Ettu)", hi: "आठ (Aath)", es: "Ocho", fr: "Huit" },
    { en: "nine", ta: "ஒன்பது (Ombodhu)", hi: "नौ (Nau)", es: "Nueve", fr: "Neuf" },
    { en: "ten", ta: "பத்து (Pathu)", hi: "दस (Das)", es: "Diez", fr: "Dix" },
    { en: "hundred", ta: "நூறு (Nooru)", hi: "सौ (Sau)", es: "Cien", fr: "Cent" },
    { en: "thousand", ta: "ஆயிரம் (Aayiram)", hi: "हज़ार (Hazaar)", es: "Mil", fr: "Mille" }
];
